config/routes.rb
Rails.application.routes.draw do
  resources :blogs do
    resources :entries do
      resources :comments do
        member do
          patch 'approve'
        end
      end
    end
  end

  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get     'top',     to: 'top#new'
  #post    'top',    to: 'top#index'
  post    'top',     to: 'top#create'

  get     'login',   to: 'logins#new'
  post    'login',   to: 'logins#create'
  delete  'logout',  to: 'logins#destroy'

  get     'main',    to: 'contents#index'
  post    'tri',     to: 'contents#tri'
  post    'era',     to: 'contents#era'

  #patch '/blogs/:blog_id/entries/:entry_id/comments/:id/approve', to: 'comments#approve'
end

app/models/blog.rb
class Blog < ApplicationRecord
  has_many :entries, dependent: :destroy
  # accepts_nested_attributes_for :entries, allow_destroy: true
  validates :title, presence: true
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  def show
    correct_routes?(%w(blogs index), %w(blogs show), %w(blogs edit),
                    %w(entries new), %w(entries create), %w(entries edit), %w(entries show))
  end

  # GET /blogs/new
  def new
    return unless correct_routes?(%w(blogs index))

    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
    correct_routes?(%w(blogs index), %w(blogs show))
  end

  # POST /blogs
  def create
    return unless correct_routes?(%w(blogs new))

    blog = Blog.new(blog_params)

    respond_to do |format|
      if blog.save
        format.html { redirect_to blogs_path, notice: 'Blog was successfully created.' }
      else
        format.html { redirect_to blogs_path, notice: blog.errors.full_messages[0] }
      end
    end
  end

  # PATCH/PUT /blogs/1
  def update
    return unless correct_routes?(%w(blogs edit))

    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to blogs_path, notice: 'Blog was successfully updated.' }
      else
        format.html { redirect_to blogs_path, notice: @blog.errors.full_messages[0] }
      end
    end
  end

  # DELETE /blogs/1
  def destroy
    return unless correct_routes?(%w(blogs index))

    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_path, notice: 'Blog was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.haml
= form_for @blog do |f|
  - if @blog.errors.any?
    #error_explanation
      %h2= "#{pluralize(@blog.errors.count, 'error')} prohibited this blog from being saved:"
      %ul
        - @blog.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :title
    = f.text_field :title
  .actions
    = f.submit 'Save'

app/views/blogs/edit.html.haml
%article
  %h2 Listing blogs
  %p
    %b Editing blog

  = render 'form'

  = link_to 'Show', @blog
  \|
  = link_to 'Back', blogs_path

app/views/blogs/index.html.haml
%article
  %h2 Listing blogs

  %table
    %thead
      %tr
        %th Title
        %th
        %th
        %th

    %tbody
      - @blogs.each do |blog|
        %tr
          %td= blog.title
          %td= link_to 'Show', blog
          %td= link_to 'Edit', edit_blog_path(blog)
          %td= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' }
  %p#notice= notice
  %br
  = link_to 'New Blog', new_blog_path

app/views/blogs/new.html.haml
%article
  %h2 Listing blogs
  %p
    %b New blog

  = render 'form'

  = link_to 'Back', blogs_path

app/views/blogs/show.html.haml
%article
  %h2 Listing blogs

  %p
    %b Title:
    = @blog.title

  = link_to 'Edit Blog', edit_blog_path(@blog)
  \|
  = link_to 'Back', blogs_path
  %br
  %br

  %h4 Listing entries
  %table
    %thead
      %tr
        %th Title
        %th Body
        %th
        %th
        %th
    %tbody
      - @blog.entries.each do |entry|
        %tr
          %td= entry.title
          %td= entry.body
          %td= link_to 'Show', blog_entry_path(@blog, entry)
          %td= link_to 'Edit', edit_blog_entry_path(@blog, entry)
          %td= link_to 'Destroy', blog_entry_path(@blog, entry), method: :delete, data: { confirm: 'Are you sure?' }
  %p#notice= notice
  = link_to 'New Entry', new_blog_entry_path(@blog)