config/routes.rb
Rails.application.routes.draw do
  resources :blogs do
    resources :entries do
      resources :comments do
        member do
          patch 'approve'
        end
      end
    end
  end

  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get     'top',     to: 'top#new'
  #post    'top',    to: 'top#index'
  post    'top',     to: 'top#create'

  get     'login',   to: 'logins#new'
  post    'login',   to: 'logins#create'
  delete  'logout',  to: 'logins#destroy'

  get     'main',    to: 'contents#index'
  post    'tri',     to: 'contents#tri'
  post    'era',     to: 'contents#era'

  #patch '/blogs/:blog_id/entries/:entry_id/comments/:id/approve', to: 'comments#approve'
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :blog
  has_many :comments, dependent: :destroy
  # accepts_nested_attributes_for :comments, allow_destroy: true
  validates :title, presence: true
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update, :destroy]

  # GET /entries/1
  def show
    unless params[:permission].eql? 'admin'
      return unless correct_routes?(%w(blogs show), %w(entries edit), %w(entries show))
    end

    @comment = Comment.new(entry_id: params[:id], status: 'unapproved')
  end

  # GET /entries/new
  def new
    return unless correct_routes?(%w(blogs show))

    @entry = Entry.new(blog_id: params[:blog_id])
  end

  # GET /entries/1/edit
  def edit
    correct_routes?(%w(blogs show), %w(entries show))
  end

  # POST /entries
  def create
    return unless correct_routes?(%w(entries new))

    entry = Entry.new(entry_params)
    respond_to do |format|
      if entry.save
        format.html { redirect_to blog_path(entry.blog), notice: 'Entry was successfully created.' }
      else
        format.html { redirect_to blog_path(entry.blog), notice: entry.errors.full_messages[0] }
      end
    end
  end

  # PATCH/PUT /entries/1
  def update
    return unless correct_routes?(%w(entries edit))

    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to blog_path(@entry.blog), notice: 'Entry was successfully updated.' }
      else
        format.html { redirect_to blog_path(@entry.blog), notice: @entry.errors.full_messages[0] }
      end
    end
  end

  # DELETE /entries/1
  def destroy
    return unless correct_routes?(%w(blogs show))

    @entry.destroy
    respond_to do |format|
      format.html { redirect_to blog_path(@entry.blog), notice: 'Entry was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entry_params
      params.require(:entry).permit(:title, :body, :blog_id)
    end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_form_comment.html.haml
= form_for(@comment, url: blog_entry_comments_path(@entry.blog, @entry, @comment)) do |f|
  - if @comment.errors.any?
    #error_explanation
      %h2= "#{pluralize(@comment.errors.count, 'error')} prohibited this comment from being saved:"
      %ul
        - @comment.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :body
    = f.text_area :body
  .field
    = f.hidden_field :status
  .field
    = f.hidden_field :entry_id
  .actions
    = f.submit 'Save'

app/views/entries/_form_create.html.haml
= form_for(@entry, url: blog_entries_path(@entry.blog, @entry)) do |f|
  - if @entry.errors.any?
    #error_explanation
      %h2= "#{pluralize(@entry.errors.count, 'error')} prohibited this entry from being saved:"
      %ul
        - @entry.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :body
    = f.text_area :body
  .field
    = f.hidden_field :blog_id
  .actions
    = f.submit 'Save'

app/views/entries/_form_update.html.haml
= form_for(@entry, url: blog_entry_path(@entry.blog, @entry), method: 'PATCH') do |f|
  - if @entry.errors.any?
    #error_explanation
      %h2= "#{pluralize(@entry.errors.count, 'error')} prohibited this entry from being saved:"
      %ul
        - @entry.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :body
    = f.text_area :body
  .field
    = f.hidden_field :blog_id
  .actions
    = f.submit 'Save'

app/views/entries/edit.html.haml
%article
  %h2 Listing blogs

  %h4 Editing entry

  = render 'form_update'

  = link_to 'Back', blog_entry_path(@entry.blog, @entry)

app/views/entries/new.html.haml
%article
  %h2 Listing blogs
  %p
    %b New entry :
    =session[:blog_title]

  = render 'form_create'

  = link_to 'Back', blog_path(@entry.blog)

app/views/entries/show.html.haml
%article
  %h2 Listing blogs

  =@entry.blog.title
  %br
  %br

  %p
    %b Title:
    = @entry.title
  %p
    %b Body:
    = @entry.body

  = link_to 'Edit Entry', edit_blog_entry_path(@entry.blog, @entry)
  \|
  = link_to 'Back', blog_path(@entry.blog)
  %br
  %br

  %table
    %thead
      %tr
        %th Body
        %th Status
        %th

    %tbody
      - @entry.comments.each do |comment|
        %tr
          %td= (comment.status.eql? 'unapproved') ? label_tag('(承認待ち)') + comment.body : comment.body
          %td= (comment.status.eql? 'unapproved') ? link_to('Approve', approve_blog_entry_comment_path(@entry.blog, @entry, comment), method: 'PATCH') : label_tag('       ')
          %td= link_to 'Destroy', blog_entry_comment_path(@entry.blog, @entry, comment.id), method: :delete, data: { confirm: 'Are you sure?' }
  %p#notice= notice
  %br
  %h4 New comment

  = render 'form_comment'